name: Upload Game
on:
  issues:
    types: [opened, edited]
jobs:
  upload-game:
    if: contains(github.event.issue.labels.*.name, 'game-upload')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      
      - name: Create games directory if it doesn't exist
        run: mkdir -p games
      
      - name: Extract game information
        id: extract
        run: |
          ISSUE_BODY="${{ github.event.issue.body }}"
          FILENAME=$(echo "$ISSUE_BODY" | grep -oP '(?<=- Filename: ).*(?=\\r|$)')
          ENCODED_CONTENT=$(echo "$ISSUE_BODY" | sed -n '/^```$/,/^```$/p' | grep -v '```')
          echo "filename=$FILENAME" >> $GITHUB_OUTPUT
          echo "content=$ENCODED_CONTENT" >> $GITHUB_ENV
      
      - name: Decode and save game
        run: |
          echo "${{ env.content }}" | base64 --decode > "games/${{ steps.extract.outputs.filename }}"
      
      - name: Commit and push
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add games/
          git commit -m "Add game: ${{ steps.extract.outputs.filename }}"
          git push
      
      - name: Close issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: "Game has been uploaded successfully! It will be available at: https://andres9890.github.io/game-maker/games/${{ steps.extract.outputs.filename }}"
